/* ==========================================================================
   catalog.js
   Dados de referência: tipos de equipamento, frequências de CQ e o acervo
   de testes vinculáveis a módulos da biblioteca pylinac (Python), além da
   opção de teste "manual" (genérico, sem vínculo com pylinac).

   Os módulos com requiresFiles=true são executados de verdade pelo backend
   Python (pasta /backend) a partir de arquivos DICOM enviados pelo usuário:
   os parâmetros listados em cada módulo correspondem exatamente aos
   argumentos aceitos pelo pylinac (analyze() ou construtor), e as métricas
   usam os nomes de campo reais devolvidos por pylinac's results_data().
   ========================================================================== */

(function (global) {
  "use strict";

  // ------------------------------------------------------------------
  // Tipos de equipamento
  // ------------------------------------------------------------------
  const EQUIPMENT_TYPES = {
    linac: { label: "Acelerador Linear", short: "LINAC" },
    ct: { label: "Tomógrafo (CT / CBCT)", short: "CT" },
    brachy: { label: "Braquiterapia", short: "BRAQUI" },
    ortho: { label: "Ortovoltagem", short: "ORTHO" },
    other: { label: "Outro equipamento", short: "OUTRO" },
  };

  // ------------------------------------------------------------------
  // Frequências de controle de qualidade
  // ------------------------------------------------------------------
  const FREQUENCIES = {
    diario: { label: "Diário", days: 1 },
    semanal: { label: "Semanal", days: 7 },
    mensal: { label: "Mensal", days: 30 },
    trimestral: { label: "Trimestral", days: 91 },
    semestral: { label: "Semestral", days: 182 },
    anual: { label: "Anual", days: 365 },
  };

  // type: 'number' | 'text' | 'select' | 'checkbox'
  // tolType: 'max' (valor <= tol), 'min' (valor >= tol),
  //          'range' (tolLow <= valor <= tolHigh), 'bool', 'info' (sem tolerância)
  // fileMode: 'single' | 'multiple' | 'pair' | 'series' (só quando requiresFiles=true)

  const PYLINAC_CATALOG = [
    // ============== LINAC: geometria de imagem / MLC (análise automática) ==============
    {
      id: "picketfence",
      name: "Picket Fence (posicionamento de MLC)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.picketfence.PicketFence",
      applicableTypes: ["linac"],
      description: "Avalia o posicionamento das lâminas do MLC a partir de uma imagem de picket fence em EPID.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do EPID (picket fence).",
      params: [
        {
          key: "mlc",
          label: "Modelo do MLC",
          type: "select",
          options: ["MILLENNIUM", "HD_MILLENNIUM", "BMOD", "AGILITY", "MLCI", "HALCYON_DISTAL", "HALCYON_PROXIMAL"],
          optionLabels: {
            MILLENNIUM: "Millennium (Varian)",
            HD_MILLENNIUM: "HD Millennium (Varian)",
            BMOD: "B Mod",
            AGILITY: "Agility (Elekta)",
            MLCI: "MLCi (Elekta)",
            HALCYON_DISTAL: "Halcyon distal (Varian)",
            HALCYON_PROXIMAL: "Halcyon proximal (Varian)",
          },
          default: "MILLENNIUM",
        },
        {
          key: "orientation",
          label: "Orientação dos pickets",
          type: "select",
          options: ["", "Up-Down", "Left-Right"],
          optionLabels: { "": "Automático (detectar — recomendado)", "Up-Down": "Up-Down (forçar)", "Left-Right": "Left-Right (forçar)" },
          default: "",
        },
        { key: "tolerance_mm", label: "Tolerância", type: "number", default: 0.5, unit: "mm", step: 0.05 },
        { key: "action_tolerance_mm", label: "Nível de ação (opcional)", type: "number", default: "", unit: "mm", step: 0.05 },
        { key: "crop_mm", label: "Corte nas bordas da imagem (crop)", type: "number", default: 3, unit: "mm", step: 1 },
        { key: "num_pickets", label: "Número de pickets (opcional, auto se vazio)", type: "number", default: "", step: 1 },
        {
          key: "picket_spacing_mm",
          label: "Espaçamento nominal entre pickets (opcional, auto se vazio)",
          type: "number",
          default: "",
          unit: "mm",
          step: 1,
        },
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "max_error_mm", label: "Erro máximo de lâmina", unit: "mm", tolType: "max", tol: 0.5 },
        { key: "absolute_median_error_mm", label: "Erro mediano absoluto", unit: "mm", tolType: "max", tol: 0.3 },
        { key: "percent_leaves_passing", label: "% de lâminas aprovadas", unit: "%", tolType: "min", tol: 100 },
        { key: "mean_picket_spacing_mm", label: "Espaçamento médio entre pickets", unit: "mm", tolType: "info" },
        { key: "mlc_skew", label: "Desvio angular (skew) do MLC", unit: "graus", tolType: "info" },
        { key: "number_of_pickets", label: "Nº de pickets detectados", unit: "", tolType: "info" },
        { key: "passed", label: "Aprovado (pylinac)", unit: "", tolType: "bool", plottable: false },
      ],
    },
    {
      id: "starshot",
      name: "Starshot (isocentro de irradiação)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.starshot.Starshot",
      applicableTypes: ["linac"],
      description: "Determina o diâmetro do menor círculo que intercepta todas as retas de um teste de estrela (colimador/gantry/mesa).",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm,.tif,.tiff,.jpg,.jpeg,.png",
      fileHint: "1 imagem (EPID DICOM, ou filme/TIFF escaneado).",
      params: [
        { key: "tolerance_mm", label: "Tolerância (diâmetro)", type: "number", default: 1.0, unit: "mm", step: 0.05 },
        { key: "radius", label: "Raio de varredura (fração do campo)", type: "number", default: 0.85, step: 0.05 },
        { key: "recursive", label: "Busca recursiva do centro", type: "checkbox", default: true },
        { key: "sid_mm", label: "SID — só p/ imagens não-DICOM (filme/TIFF)", type: "number", default: "", unit: "mm", step: 1 },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "circle_diameter_mm", label: "Diâmetro do wobble", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "passed", label: "Aprovado (pylinac)", unit: "", tolType: "bool", plottable: false },
      ],
    },
    {
      id: "winston_lutz",
      name: "Winston-Lutz (isocentro mecânico/radiante)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.winston_lutz.WinstonLutz",
      applicableTypes: ["linac"],
      description: "Avalia a coincidência entre o isocentro de radiação e o isocentro mecânico usando um conjunto de imagens de EPID de uma esfera (BB) em diferentes ângulos.",
      requiresFiles: true,
      fileMode: "multiple",
      fileAccept: ".dcm",
      fileHint: "Todas as imagens DICOM do conjunto Winston-Lutz (várias combinações de gantry/colimador/mesa).",
      params: [
        { key: "bb_size_mm", label: "Diâmetro da esfera (BB)", type: "number", default: 5, unit: "mm", step: 0.5 },
        {
          key: "machine_scale",
          label: "Escala da máquina",
          type: "select",
          options: ["IEC61217", "VARIAN_STANDARD", "ELEKTA_IEC"],
          optionLabels: { IEC61217: "IEC 61217 (padrão)", VARIAN_STANDARD: "Varian Standard", ELEKTA_IEC: "Elekta IEC" },
          default: "IEC61217",
        },
        { key: "low_density_bb", label: "BB de baixa densidade", type: "checkbox", default: false },
        { key: "open_field", label: "Campo aberto (sem MLC definindo o campo)", type: "checkbox", default: false },
        { key: "bb_proximity_mm", label: "Proximidade esperada da BB", type: "number", default: 20, unit: "mm", step: 1 },
        {
          key: "field_edge_threshold_pct",
          label: "Limiar da borda de campo (imagem individual)",
          type: "number",
          default: 50,
          unit: "%",
          step: 1,
        },
        {
          key: "bb_threshold_pct",
          label: "Limiar da borda da BB (imagem individual)",
          type: "number",
          default: 50,
          unit: "%",
          step: 1,
        },
        {
          key: "action_level_mm",
          label: "Nível de ação — Erro 2D CAX→BB (opcional, deve ser menor que a tolerância abaixo)",
          type: "number",
          default: "",
          unit: "mm",
          step: 0.1,
        },
      ],
      metrics: [
        { key: "max_2d_cax_to_bb_mm", label: "Erro 2D máx. CAX→BB (tolerância)", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "median_2d_cax_to_bb_mm", label: "Erro 2D mediano CAX→BB", unit: "mm", tolType: "info" },
        { key: "gantry_3d_iso_diameter_mm", label: "Isocentro 3D do gantry", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "coll_2d_iso_diameter_mm", label: "Isocentro do colimador", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "couch_2d_iso_diameter_mm", label: "Isocentro da mesa", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "max_2d_cax_to_epid_mm", label: "Erro 2D máx. CAX→EPID", unit: "mm", tolType: "max", tol: 2.0 },
      ],
    },
    {
      id: "field_analysis",
      name: "Field Analysis (Flatness & Symmetry)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.field_analysis.FieldAnalysis",
      applicableTypes: ["linac"],
      description: "Planeza, simetria e tamanho de campo a partir de uma imagem de EPID.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do EPID com o campo aberto.",
      params: [
        {
          key: "protocol",
          label: "Protocolo",
          type: "select",
          options: ["VARIAN", "ELEKTA", "SIEMENS", "NONE"],
          optionLabels: { VARIAN: "Varian", ELEKTA: "Elekta", SIEMENS: "Siemens", NONE: "Nenhum (genérico)" },
          default: "VARIAN",
        },
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "is_FFF", label: "Feixe sem filtro (FFF)", type: "checkbox", default: false },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "protocol_results.flatness_horizontal", label: "Planeza horizontal", unit: "%", tolType: "max", tol: 3.0 },
        { key: "protocol_results.flatness_vertical", label: "Planeza vertical", unit: "%", tolType: "max", tol: 3.0 },
        { key: "protocol_results.symmetry_horizontal", label: "Simetria horizontal", unit: "%", tolType: "max", tol: 2.0 },
        { key: "protocol_results.symmetry_vertical", label: "Simetria vertical", unit: "%", tolType: "max", tol: 2.0 },
        { key: "field_size_horizontal_mm", label: "Tamanho de campo (horizontal)", unit: "mm", tolType: "info" },
        { key: "field_size_vertical_mm", label: "Tamanho de campo (vertical)", unit: "mm", tolType: "info" },
      ],
    },
    {
      id: "isoalign",
      name: "IsoAlign (coincidência campo luminoso × radiação)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.planar_imaging.IsoAlign",
      applicableTypes: ["linac"],
      description:
        "Verifica a coincidência entre o campo luminoso (posição das esferas/BBs marcadas manualmente com o campo de luz) e o campo de radiação real, usando o fantoma PTW Iso-Align.",
      // O IsoAlign é feito com o fantoma parado (não repetido em vários
      // ângulos de gantry, como picket fence/starshot) — o ângulo de gantry
      // lido do DICOM não varia de forma relevante entre resultados, então
      // o filtro por Gantry na tela da rotina não faz sentido aqui.
      excludeGantryFilter: true,
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do EPID com o fantoma Iso-Align (campo aberto + esferas/BBs posicionadas com o campo de luz).",
      params: [
        { key: "fwxm", label: "FWXM para detecção do campo", type: "number", default: 50, unit: "%", step: 1 },
        { key: "bb_edge_threshold_mm", label: "Limiar de borda da BB", type: "number", default: 3, unit: "mm", step: 0.5 },
        {
          key: "kernel_size_multiplier",
          label: "Multiplicador do kernel (detecção de BB)",
          type: "number",
          default: 2.0,
          step: 0.1,
        },
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "crop_px", label: "Recorte de borda da imagem (px)", type: "number", default: 100, unit: "px", step: 10 },
        {
          key: "collimation_type",
          label: "Colimação testada",
          type: "select",
          options: ["jaws", "mlc"],
          optionLabels: { jaws: "JAWS (colimador secundário)", mlc: "MLC (colimador multilâminas)" },
          default: "jaws",
        },
        {
          key: "symmetry",
          label: "Simetria do campo nominal",
          type: "select",
          options: ["symmetric", "asymmetric"],
          optionLabels: { symmetric: "Simétrico", asymmetric: "Assimétrico" },
          default: "symmetric",
        },
        { key: "nominal_x1_mm", label: "Tamanho nominal de campo — X1", type: "number", default: 100, unit: "mm", step: 1 },
        { key: "nominal_x2_mm", label: "Tamanho nominal de campo — X2", type: "number", default: 100, unit: "mm", step: 1 },
        { key: "nominal_y1_mm", label: "Tamanho nominal de campo — Y1", type: "number", default: 100, unit: "mm", step: 1 },
        { key: "nominal_y2_mm", label: "Tamanho nominal de campo — Y2", type: "number", default: 100, unit: "mm", step: 1 },
        {
          key: "bb_line_width",
          label: "Espessura da linha — BB",
          type: "number",
          default: 1.5,
          step: 0.1,
        },
        {
          key: "epid_line_width",
          label: "Espessura da linha — EPID",
          type: "number",
          default: 1.5,
          step: 0.1,
        },
        {
          key: "field_line_width",
          label: "Espessura da linha — Field (centro do campo)",
          type: "number",
          default: 1.5,
          step: 0.1,
        },
        {
          key: "field_edge_line_width",
          label: "Espessura da linha — Borda de campo (FWXM)",
          type: "number",
          default: 0.6,
          step: 0.1,
        },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "field_size_x_mm", label: "Tamanho de campo medido (X / crossplane)", unit: "mm", tolType: "info", plottable: false },
        { key: "field_size_y_mm", label: "Tamanho de campo medido (Y / inplane)", unit: "mm", tolType: "info", plottable: false },
        { key: "nominal_field_size_x_mm", label: "Tamanho de campo nominal (X = X1+X2)", unit: "mm", tolType: "info", plottable: false },
        { key: "nominal_field_size_y_mm", label: "Tamanho de campo nominal (Y = Y1+Y2)", unit: "mm", tolType: "info", plottable: false },
        {
          key: "field_size_x_deviation_mm",
          label: "Desvio campo medido × nominal (X)",
          unit: "mm",
          tolType: "range",
          tolLow: -2.0,
          tolHigh: 2.0,
        },
        {
          key: "field_size_y_deviation_mm",
          label: "Desvio campo medido × nominal (Y)",
          unit: "mm",
          tolType: "range",
          tolLow: -2.0,
          tolHigh: 2.0,
        },
        { key: "field_epid_offset_x_mm", label: "Desvio campo → centro do EPID (X)", unit: "mm", tolType: "info", plottable: false },
        { key: "field_epid_offset_y_mm", label: "Desvio campo → centro do EPID (Y)", unit: "mm", tolType: "info", plottable: false },
        {
          key: "field_bb_offset_x_mm",
          label: "Desvio campo → BB / Luz×Rad (X)",
          unit: "mm",
          tolType: "range",
          tolLow: -1.0,
          tolHigh: 1.0,
        },
        {
          key: "field_bb_offset_y_mm",
          label: "Desvio campo → BB / Luz×Rad (Y)",
          unit: "mm",
          tolType: "range",
          tolLow: -1.0,
          tolHigh: 1.0,
        },
        { key: "max_light_rad_error_mm", label: "Erro máximo Luz × Rad", unit: "mm", tolType: "max", tol: 2.0 },
      ],
    },
    {
      id: "vmat_drgs",
      name: "VMAT - DRGS (Dose Rate & Gantry Speed)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.vmat.DRGS",
      applicableTypes: ["linac"],
      description: "Teste VMAT de variação de taxa de dose e velocidade de gantry.",
      requiresFiles: true,
      fileMode: "pair",
      fileAccept: ".dcm",
      fileLabels: ["Campo aberto (Open)", "Campo DRGS"],
      params: [{ key: "tolerance_percent", label: "Tolerância", type: "number", default: 1.5, unit: "%", step: 0.1 }],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "max_deviation_percent", label: "Desvio máximo", unit: "%", tolType: "max", tol: 1.5 },
        { key: "abs_mean_deviation", label: "Desvio médio absoluto", unit: "%", tolType: "info" },
        { key: "passed", label: "Aprovado (pylinac)", unit: "", tolType: "bool", plottable: false },
      ],
    },
    {
      id: "vmat_drmlc",
      name: "VMAT - DRMLC (Dose Rate & MLC Speed)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.vmat.DRMLC",
      applicableTypes: ["linac"],
      description: "Teste VMAT de variação de taxa de dose e velocidade das lâminas do MLC.",
      requiresFiles: true,
      fileMode: "pair",
      fileAccept: ".dcm",
      fileLabels: ["Campo aberto (Open)", "Campo DRMLC"],
      params: [{ key: "tolerance_percent", label: "Tolerância", type: "number", default: 1.5, unit: "%", step: 0.1 }],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "max_deviation_percent", label: "Desvio máximo", unit: "%", tolType: "max", tol: 1.5 },
        { key: "abs_mean_deviation", label: "Desvio médio absoluto", unit: "%", tolType: "info" },
        { key: "passed", label: "Aprovado (pylinac)", unit: "", tolType: "bool", plottable: false },
      ],
    },

    // ============== Imagem Planar — EPID/kV (análise automática) ==============
    {
      id: "planar_leeds",
      name: "Imagem Planar - Leeds TOR (kV)",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.LeedsTOR",
      applicableTypes: ["linac", "ortho", "ct"],
      description: "Qualidade de imagem kV com o fantoma Leeds TOR (contraste, uniformidade).",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "num_contrast_rois_seen", label: "ROIs de contraste detectados", unit: "", tolType: "info" },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_qc3",
      name: "Imagem Planar - Standard Imaging QC-3",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.StandardImagingQC3",
      applicableTypes: ["linac"],
      description: "Qualidade de imagem MV/kV com o fantoma QC-3.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "num_contrast_rois_seen", label: "ROIs de contraste detectados", unit: "", tolType: "info" },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_lasvegas",
      name: "Imagem Planar - Las Vegas",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.LasVegas",
      applicableTypes: ["linac"],
      description: "Avaliação de contraste de baixo relevo com o fantoma Las Vegas.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "num_contrast_rois_seen", label: "ROIs de contraste detectados", unit: "", tolType: "info" },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_doselab_kv",
      name: "Imagem Planar - Doselab MC2 (kV)",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.DoselabMC2kV",
      applicableTypes: ["linac"],
      description: "QA de imagem kV com fantoma Doselab MC2.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_doselab_mv",
      name: "Imagem Planar - Doselab MC2 (MV)",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.DoselabMC2MV",
      applicableTypes: ["linac"],
      description: "QA de imagem MV (EPID) com fantoma Doselab MC2.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_snc_kv",
      name: "Imagem Planar - SNC kV",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.SNCkV",
      applicableTypes: ["linac"],
      description: "QA de imagem kV com fantoma Sun Nuclear.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },
    {
      id: "planar_snc_mv",
      name: "Imagem Planar - SNC MV",
      group: "Imagem Planar (EPID / kV)",
      pylinacRef: "pylinac.planar_imaging.SNCMV",
      applicableTypes: ["linac"],
      description: "QA de imagem MV (EPID) com fantoma Sun Nuclear.",
      requiresFiles: true,
      fileMode: "single",
      fileAccept: ".dcm",
      fileHint: "1 imagem DICOM do fantoma.",
      params: [
        { key: "invert", label: "Inverter imagem", type: "checkbox", default: false },
        { key: "ssd", label: "SSD (mm ou 'auto')", type: "text", default: "auto" },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "median_contrast", label: "Contraste mediano", unit: "", tolType: "info" },
        { key: "median_cnr", label: "CNR mediano", unit: "", tolType: "min", tol: 3 },
        { key: "percent_integral_uniformity", label: "Uniformidade integral", unit: "%", tolType: "min", tol: 80 },
      ],
    },

    // ============== CT / CBCT (análise automática) ==============
    {
      id: "catphan",
      name: "CatPhan (CT / CBCT)",
      group: "Tomógrafo (CT / CBCT)",
      pylinacRef: "pylinac.ct.CatPhan504 / CatPhan503 / CatPhan600 / CatPhan604",
      applicableTypes: ["ct"],
      description: "Avaliação de HU, geometria, uniformidade e resolução com fantoma CatPhan.",
      requiresFiles: true,
      fileMode: "series",
      fileAccept: ".dcm,.zip",
      fileHint: "Todos os cortes DICOM da série (ou um único arquivo .zip contendo a série).",
      params: [
        { key: "phantom_model", label: "Modelo do fantoma", type: "select", options: ["CatPhan 504", "CatPhan 503", "CatPhan 600", "CatPhan 604"], default: "CatPhan 504" },
        { key: "hu_tolerance", label: "Tolerância de HU", type: "number", default: 40, unit: "HU", step: 1 },
        { key: "scaling_tolerance_mm", label: "Tolerância geométrica", type: "number", default: 1.0, unit: "mm", step: 0.1 },
        { key: "thickness_tolerance_mm", label: "Tolerância de espessura de corte", type: "number", default: 0.2, unit: "mm", step: 0.1 },
      ],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "ctp404.hu_linearity_passed", label: "Linearidade de HU aprovada", unit: "", tolType: "bool" },
        { key: "ctp404.geometry_passed", label: "Precisão geométrica aprovada", unit: "", tolType: "bool" },
        { key: "ctp404.thickness_passed", label: "Espessura de corte aprovada", unit: "", tolType: "bool" },
        { key: "ctp404.measured_slice_thickness_mm", label: "Espessura de corte medida", unit: "mm", tolType: "info" },
        { key: "ctp404.avg_line_distance_mm", label: "Distância média entre linhas (geometria)", unit: "mm", tolType: "info" },
        { key: "ctp404.low_contrast_visibility", label: "Visibilidade de baixo contraste", unit: "", tolType: "info" },
        { key: "ctp486.passed", label: "Uniformidade aprovada", unit: "", tolType: "bool" },
        { key: "ctp486.integral_non_uniformity", label: "Não-uniformidade integral", unit: "", tolType: "info" },
      ],
    },
    {
      id: "quart",
      name: "Quart DVT (CBCT)",
      group: "Tomógrafo (CT / CBCT)",
      pylinacRef: "pylinac.quart.QuartDVT",
      applicableTypes: ["ct"],
      description: "QA de CBCT com fantoma Quart (HU, distorção geométrica, uniformidade).",
      requiresFiles: true,
      fileMode: "series",
      fileAccept: ".dcm,.zip",
      fileHint: "Todos os cortes DICOM da série CBCT (ou um único arquivo .zip).",
      params: [{ key: "hu_tolerance", label: "Tolerância de HU", type: "number", default: 40, unit: "HU", step: 1 }],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "uniformity_module.passed", label: "Uniformidade aprovada", unit: "", tolType: "bool" },
        { key: "hu_module.signal_to_noise", label: "Relação sinal-ruído (HU)", unit: "", tolType: "info" },
        { key: "hu_module.contrast_to_noise", label: "Relação contraste-ruído (HU)", unit: "", tolType: "info" },
        { key: "hu_module.measured_slice_thickness_mm", label: "Espessura de corte medida", unit: "mm", tolType: "info" },
        { key: "geometric_module.mean_high_contrast_distance", label: "Distância média (geometria)", unit: "mm", tolType: "info" },
      ],
    },
    {
      id: "cheese",
      name: "Cheese Phantom / TomoCheese",
      group: "Tomógrafo (CT / CBCT)",
      pylinacRef: "pylinac.cheese.TomoCheese",
      applicableTypes: ["ct"],
      description: "Avaliação de HU por inserções em fantoma tipo 'queijo' (uso em TomoTherapy e CBCT).",
      requiresFiles: true,
      fileMode: "series",
      fileAccept: ".dcm,.zip",
      fileHint: "Todos os cortes DICOM da série (ou um único arquivo .zip).",
      params: [],
      metrics: [
        { key: "dicom_gantry_angle_deg", label: "Ângulo do Gantry", unit: "°", tolType: "info", plottable: false },
        { key: "dicom_collimator_angle_deg", label: "Ângulo do Colimador", unit: "°", tolType: "info", plottable: false },
        { key: "phantom_roll", label: "Rotação (roll) do fantoma", unit: "graus", tolType: "info" },
        { key: "num_images", label: "Nº de cortes analisados", unit: "", tolType: "info" },
      ],
    },

    // ============== Módulos sem análise automática (lançamento manual) ==============
    {
      id: "winston_lutz_mtmf",
      name: "Winston-Lutz Multi-Alvo/Multi-Campo",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.winston_lutz.WinstonLutzMultiTargetMultiField",
      applicableTypes: ["linac"],
      description: "Winston-Lutz para técnicas estereotáxicas com múltiplos alvos/campos (ex.: SRS multi-lesão).",
      requiresFiles: false,
      autoAnalysisNote: "Requer a configuração exata do arranjo de esferas (bb_arrangement) do fantoma do fabricante — lance os resultados manualmente após rodar o pylinac.",
      params: [
        { key: "bb_arrangement", label: "Arranjo de esferas (referência)", type: "text", default: "Padrão do fantoma" },
        { key: "tolerance_mm", label: "Tolerância por alvo", type: "number", default: 1.0, unit: "mm", step: 0.05 },
      ],
      metrics: [
        { key: "max_bb_error_mm", label: "Erro máximo por esfera", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "mean_bb_error_mm", label: "Erro médio", unit: "mm", tolType: "max", tol: 0.5 },
      ],
    },
    {
      id: "dlg",
      name: "DLG - Dosimetric Leaf Gap",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.dlg.DLG",
      applicableTypes: ["linac"],
      description: "Estimativa do gap dosimétrico das lâminas do MLC.",
      requiresFiles: false,
      autoAnalysisNote: "Requer a sequência de gaps testados e o tipo de MLC como configuração adicional — lance o resultado calculado manualmente.",
      params: [{ key: "tolerance_mm", label: "Tolerância", type: "number", default: 0.2, unit: "mm", step: 0.05 }],
      metrics: [{ key: "dlg_mm", label: "DLG calculado", unit: "mm", tolType: "range", tolLow: -0.5, tolHigh: 0.5 }],
    },
    {
      id: "acr_ct",
      name: "ACR CT",
      group: "Tomógrafo (CT / CBCT)",
      pylinacRef: "pylinac.acr.ACRCT",
      applicableTypes: ["ct"],
      description: "Programa de acreditação ACR para tomografia computadorizada.",
      requiresFiles: false,
      autoAnalysisNote: "A estrutura de resultado do módulo ACR é muito detalhada por módulo do fantoma — lance os valores relevantes manualmente após revisar o relatório do pylinac.",
      params: [{ key: "hu_tolerance", label: "Tolerância de HU", type: "number", default: 40, unit: "HU", step: 1 }],
      metrics: [
        { key: "hu_linearity_max_error", label: "Erro máx. de linearidade de HU", unit: "HU", tolType: "max", tol: 40 },
        { key: "geometry_mm", label: "Precisão geométrica", unit: "mm", tolType: "max", tol: 1.0 },
        { key: "uniformity_hu", label: "Uniformidade", unit: "HU", tolType: "max", tol: 40 },
        { key: "low_contrast_visibility", label: "Visibilidade de baixo contraste", unit: "", tolType: "info" },
      ],
    },
    {
      id: "acr_mri",
      name: "ACR MRI",
      group: "Tomógrafo (CT / CBCT)",
      pylinacRef: "pylinac.acr.ACRMRILarge / ACRMRIMedium",
      applicableTypes: ["ct", "other"],
      description: "Programa de acreditação ACR para ressonância magnética.",
      requiresFiles: false,
      autoAnalysisNote: "A estrutura de resultado do módulo ACR é muito detalhada por módulo do fantoma — lance os valores relevantes manualmente após revisar o relatório do pylinac.",
      params: [{ key: "geometric_tolerance_mm", label: "Tolerância de precisão geométrica", type: "number", default: 2.0, unit: "mm", step: 0.1 }],
      metrics: [
        { key: "geometric_accuracy_mm", label: "Precisão geométrica", unit: "mm", tolType: "max", tol: 2.0 },
        { key: "slice_thickness_mm", label: "Espessura de corte", unit: "mm", tolType: "info" },
        { key: "uniformity", label: "Uniformidade de imagem", unit: "%", tolType: "info" },
        { key: "ghosting_percent", label: "Ghosting", unit: "%", tolType: "max", tol: 3.0 },
      ],
    },
    {
      id: "log_analyzer",
      name: "Análise de Log de Trajetória (Trajectory Log)",
      group: "Acelerador Linear",
      pylinacRef: "pylinac.log_analyzer.TrajectoryLog",
      applicableTypes: ["linac"],
      description: "Compara posições planejadas x executadas do MLC/gantry a partir dos logs da máquina (análise gama).",
      requiresFiles: false,
      autoAnalysisNote: "A API de log do pylinac usa gráficos de fluência/gama interativos em vez de um resumo numérico único — rode localmente em Python e lance os resultados aqui.",
      params: [
        { key: "gamma_dose_tolerance_percent", label: "Tolerância de dose (gama)", type: "number", default: 1.0, unit: "%", step: 0.1 },
        { key: "gamma_distance_tolerance_mm", label: "Tolerância de distância (gama)", type: "number", default: 1.0, unit: "mm", step: 0.1 },
      ],
      metrics: [
        { key: "gamma_pass_rate_percent", label: "Taxa de aprovação gama", unit: "%", tolType: "min", tol: 95 },
        { key: "max_mlc_error_mm", label: "Erro máximo de MLC", unit: "mm", tolType: "max", tol: 1.0 },
      ],
    },
    {
      id: "tg51_photon",
      name: "Calibração TG-51 - Fótons",
      group: "Calibração / Dosimetria",
      pylinacRef: "pylinac.calibration.tg51.TG51Photon",
      applicableTypes: ["linac", "ortho"],
      description: "Calibração absoluta de feixes de fótons segundo o protocolo TG-51 (AAPM). Calculadora numérica — não usa imagens.",
      requiresFiles: false,
      autoAnalysisNote: "Este módulo é uma calculadora a partir de leituras de câmara/eletrômetro, não uma análise de imagem — não há arquivo para enviar.",
      params: [
        { key: "energy_MV", label: "Energia nominal", type: "text", default: "6X" },
        { key: "temperature_c", label: "Temperatura", type: "number", default: 22, unit: "°C", step: 0.1 },
        { key: "pressure_kpa", label: "Pressão", type: "number", default: 101.3, unit: "kPa", step: 0.1 },
      ],
      metrics: [{ key: "dose_per_mu_cGy", label: "Dose por UM", unit: "cGy/UM", tolType: "range", tolLow: 0.98, tolHigh: 1.02 }],
    },
    {
      id: "tg51_electron",
      name: "Calibração TG-51 - Elétrons",
      group: "Calibração / Dosimetria",
      pylinacRef: "pylinac.calibration.tg51.TG51Electron",
      applicableTypes: ["linac"],
      description: "Calibração absoluta de feixes de elétrons segundo o protocolo TG-51 (AAPM). Calculadora numérica — não usa imagens.",
      requiresFiles: false,
      autoAnalysisNote: "Calculadora a partir de leituras de câmara — não há arquivo para enviar.",
      params: [
        { key: "energy_MeV", label: "Energia nominal", type: "text", default: "6E" },
        { key: "r50_cm", label: "R50 medido", type: "number", default: 0, unit: "cm", step: 0.01 },
      ],
      metrics: [{ key: "dose_per_mu_cGy", label: "Dose por UM", unit: "cGy/UM", tolType: "range", tolLow: 0.98, tolHigh: 1.02 }],
    },
    {
      id: "trs398_photon",
      name: "Calibração TRS-398 - Fótons",
      group: "Calibração / Dosimetria",
      pylinacRef: "pylinac.calibration.trs398.TRS398Photon",
      applicableTypes: ["linac", "ortho"],
      description: "Calibração absoluta de feixes de fótons segundo o protocolo TRS-398 (IAEA). Calculadora numérica — não usa imagens.",
      requiresFiles: false,
      autoAnalysisNote: "Calculadora a partir de leituras de câmara — não há arquivo para enviar.",
      params: [
        { key: "energy_MV", label: "Energia nominal", type: "text", default: "6X" },
        { key: "temperature_c", label: "Temperatura", type: "number", default: 22, unit: "°C", step: 0.1 },
        { key: "pressure_kpa", label: "Pressão", type: "number", default: 101.3, unit: "kPa", step: 0.1 },
      ],
      metrics: [{ key: "dose_per_mu_cGy", label: "Dose por UM", unit: "cGy/UM", tolType: "range", tolLow: 0.98, tolHigh: 1.02 }],
    },
    {
      id: "trs398_electron",
      name: "Calibração TRS-398 - Elétrons",
      group: "Calibração / Dosimetria",
      pylinacRef: "pylinac.calibration.trs398.TRS398Electron",
      applicableTypes: ["linac"],
      description: "Calibração absoluta de feixes de elétrons segundo o protocolo TRS-398 (IAEA). Calculadora numérica — não usa imagens.",
      requiresFiles: false,
      autoAnalysisNote: "Calculadora a partir de leituras de câmara — não há arquivo para enviar.",
      params: [
        { key: "energy_MeV", label: "Energia nominal", type: "text", default: "6E" },
        { key: "r50_cm", label: "R50 medido", type: "number", default: 0, unit: "cm", step: 0.01 },
      ],
      metrics: [{ key: "dose_per_mu_cGy", label: "Dose por UM", unit: "cGy/UM", tolType: "range", tolLow: 0.98, tolHigh: 1.02 }],
    },
  ];

  // ------------------------------------------------------------------
  // Teste manual / genérico (sem vínculo obrigatório com pylinac)
  // ------------------------------------------------------------------
  const MANUAL_TEST_TYPE = {
    id: "manual",
    name: "Teste manual / genérico (sem pylinac)",
    group: "Genérico",
    pylinacRef: null,
    applicableTypes: ["linac", "ct", "brachy", "ortho", "other"],
    description: "Registro manual de resultados numéricos ou aprovação/reprovação, com métricas definidas pelo usuário.",
    requiresFiles: false,
  };

  function getModulesForType(equipmentType) {
    return PYLINAC_CATALOG.filter((m) => m.applicableTypes.includes(equipmentType));
  }

  function getModuleById(id) {
    return PYLINAC_CATALOG.find((m) => m.id === id) || null;
  }

  function groupModules(modules) {
    const groups = {};
    modules.forEach((m) => {
      if (!groups[m.group]) groups[m.group] = [];
      groups[m.group].push(m);
    });
    return groups;
  }

  global.RTQC = global.RTQC || {};
  global.RTQC.catalog = {
    EQUIPMENT_TYPES,
    FREQUENCIES,
    PYLINAC_CATALOG,
    MANUAL_TEST_TYPE,
    getModulesForType,
    getModuleById,
    groupModules,
  };
})(window);
