"""
snc_watcher.py — Observa o arquivo Sncdata.fdb (banco do Sun Nuclear Daily
QA3/Atlas) em segundo plano e importa o teste diário automaticamente sempre
que o arquivo é atualizado (mesmo sem nenhum navegador aberto) — mesma ideia
de watcher.py (pastas observadas), mas o gatilho aqui é a data de
modificação de UM arquivo, não o aparecimento de arquivos novos numa pasta.

Usa varredura por polling pelo mesmo motivo de watcher.py: o arquivo
normalmente está numa pasta de rede/drive mapeado do Windows, onde eventos
de sistema de arquivos não são confiáveis.
"""

import logging
import threading

import db
from sncdata_import import read_results

logger = logging.getLogger("rtqc-backend")

POLL_INTERVAL_SECONDS = 30

_stop_event = threading.Event()
_thread = None
_last_mtime = None


def _max_imported_data_key(routine_id):
    """Maior DATA_KEY já importado para esta rotina — lido dos próprios
    resultados já gravados (rawMetrics._snc_data_key), sem precisar de uma
    tabela de estado separada. None se a rotina ainda não tem nenhum
    resultado importado."""
    best = None
    for r in db.list_results(routine_id):
        raw = r.get("rawMetrics") or {}
        dk = raw.get("_snc_data_key")
        if dk is not None and (best is None or dk > best):
            best = dk
    return best


def _sync_routine(routine, fdb_path):
    set_key = (routine.get("params") or {}).get("set_key")
    if set_key in (None, ""):
        return 0
    try:
        set_key = int(set_key)
    except (TypeError, ValueError):
        logger.warning("Rotina %s: set_key inválido (%r) — pulando sincronização.", routine["id"], set_key)
        return 0

    since = _max_imported_data_key(routine["id"])
    try:
        records = read_results(fdb_path, set_key, since_data_key=since)
    except Exception:
        logger.exception("Falha ao ler o Sncdata.fdb para a rotina %s (SET_KEY %s)", routine["id"], set_key)
        return 0

    metric_keys = {m["key"] for m in routine.get("metrics") or []}
    created = 0
    for rec in records:
        values = {k: v for k, v in rec["metrics"].items() if k in metric_keys}
        raw = dict(rec["metrics"])
        raw["_snc_data_key"] = rec["dataKey"]
        raw["_snc_set_key"] = rec["setKey"]
        raw["_snc_measured_datetime"] = rec["measuredDatetime"]
        db.create_result(
            {
                "routineId": routine["id"],
                "date": rec["date"],
                "performedByName": rec.get("signature") or "Atlas (Sun Nuclear Daily QA3)",
                "values": values,
                "notes": "Importado automaticamente do Sncdata.fdb (Sun Nuclear Daily QA3/Atlas).",
                "autoGenerated": True,
                "rawMetrics": raw,
                "sourceFiles": [],
            }
        )
        created += 1
    if created:
        logger.info(
            "Sncdata.fdb: %d resultado(s) novo(s) importado(s) para a rotina %s (SET_KEY %s).",
            created,
            routine["id"],
            set_key,
        )
    return created


def sync_now(fdb_path=None):
    """Roda a sincronização imediatamente para todas as rotinas do tipo
    snc_daily, independente do mtime — usado pelo botão "Sincronizar agora"
    e pelo próprio laço de observação. Devolve o total de resultados
    criados."""
    path = fdb_path or db.get_snc_fdb_path()
    if not path:
        return 0
    total = 0
    for routine in db.list_routines():
        if routine.get("testType") != "snc_daily" or routine.get("active") is False:
            continue
        total += _sync_routine(routine, path)
    return total


def _loop():
    global _last_mtime
    logger.info("Observador do Sncdata.fdb ativo (verificação a cada %ss).", POLL_INTERVAL_SECONDS)
    while not _stop_event.is_set():
        try:
            path = db.get_snc_fdb_path()
            if path:
                import os

                try:
                    mtime = os.stat(path).st_mtime
                except OSError as e:
                    logger.warning("Sncdata.fdb configurado (%s) mas inacessível: %s", path, e)
                    mtime = None
                if mtime is not None and mtime != _last_mtime:
                    sync_now(path)
                    _last_mtime = mtime
        except Exception:
            logger.exception("Erro no laço do observador do Sncdata.fdb")
        _stop_event.wait(POLL_INTERVAL_SECONDS)


def start():
    global _thread
    if _thread and _thread.is_alive():
        return
    _stop_event.clear()
    _thread = threading.Thread(target=_loop, daemon=True, name="rtqc-snc-watcher")
    _thread.start()


def stop():
    _stop_event.set()
