"""
watcher.py — Observa pastas locais/de rede em busca de novos arquivos DICOM
e analisa automaticamente com o pylinac, gravando o resultado direto no
banco (funciona mesmo sem nenhum navegador aberto).

Usa varredura por polling (em vez de eventos de sistema de arquivos) porque
pastas de rede mapeadas (ex.: um drive Z:\\ do Windows/SMB) frequentemente
não disparam notificações de mudança de forma confiável.
"""

import logging
import shutil
import tempfile
import threading
import time
from pathlib import Path

import db
from analysis import AnalysisError, run_analysis

logger = logging.getLogger("rtqc-backend")

POLL_INTERVAL_SECONDS = 10
STABLE_CHECKS = 2  # nº de varreduras seguidas com o mesmo tamanho de arquivo para considerá-lo "pronto"
PROCESSED_SUBDIR = "processado_cq"
FAILED_SUBDIR = "falha_cq"

_stop_event = threading.Event()
_thread = None
_file_sizes = {}  # caminho -> (tamanho, nº de checagens estáveis)


def _wait_stable(path: Path) -> bool:
    try:
        size = path.stat().st_size
    except OSError:
        return False
    prev = _file_sizes.get(str(path))
    count = prev[1] + 1 if prev and prev[0] == size else 1
    _file_sizes[str(path)] = (size, count)
    return count >= STABLE_CHECKS


def _process_file(routine: dict, file_path: Path):
    tmp_dir = tempfile.mkdtemp(prefix="rtqc_watch_")
    try:
        dest = Path(tmp_dir) / file_path.name
        shutil.copy(str(file_path), str(dest))
        result = run_analysis(routine["moduleId"], routine["params"], [dest], tmp_dir)

        values = {}
        for m in routine["metrics"]:
            v = result["metrics"].get(m["key"])
            if v is not None:
                values[m["key"]] = v

        date = result["metrics"].get("dicom_study_date") or time.strftime("%Y-%m-%d")

        db.create_result(
            {
                "routineId": routine["id"],
                "date": date,
                "performedByName": "Análise automática (pasta observada)",
                "values": values,
                "notes": f"Gerado automaticamente a partir de '{file_path.name}'.",
                "analyzedWithPylinac": True,
                "autoGenerated": True,
                "rawMetrics": result["metrics"],
                "sourceFiles": [file_path.name],
            }
        )
        logger.info("Resultado automático criado (rotina %s, arquivo %s)", routine["id"], file_path.name)
        return True
    except AnalysisError as e:
        logger.warning("Falha ao analisar automaticamente '%s': %s", file_path, e)
        return False
    except Exception:
        logger.exception("Erro inesperado ao processar '%s'", file_path)
        return False
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def _handle_watch_folder(wf: dict):
    folder = Path(wf["folderPath"])
    if not folder.is_dir():
        db.set_watch_folder_error(wf["id"], f"Pasta não encontrada ou inacessível: {wf['folderPath']}")
        return

    routine = db.get_routine(wf["routineId"])
    if not routine:
        db.set_watch_folder_error(wf["id"], "A rotina associada a esta pasta não existe mais.")
        return

    processed_dir = folder / PROCESSED_SUBDIR
    failed_dir = folder / FAILED_SUBDIR

    try:
        entries = sorted(p for p in folder.iterdir() if p.is_file())
    except OSError as e:
        db.set_watch_folder_error(wf["id"], f"Erro ao listar a pasta: {e}")
        return

    for entry in entries:
        if not _wait_stable(entry):
            continue  # arquivo ainda sendo escrito/copiado; tenta de novo na próxima varredura

        ok = _process_file(routine, entry)
        _file_sizes.pop(str(entry), None)
        target_dir = processed_dir if ok else failed_dir
        try:
            target_dir.mkdir(exist_ok=True)
            shutil.move(str(entry), str(target_dir / entry.name))
        except OSError as move_err:
            logger.warning("Não foi possível mover '%s' após processar: %s", entry, move_err)

    db.set_watch_folder_error(wf["id"], None)


def _loop():
    logger.info("Observador de pastas ativo (verificação a cada %ss).", POLL_INTERVAL_SECONDS)
    while not _stop_event.is_set():
        try:
            for wf in db.list_watch_folders(active_only=True):
                _handle_watch_folder(wf)
        except Exception:
            logger.exception("Erro no laço do observador de pastas")
        _stop_event.wait(POLL_INTERVAL_SECONDS)


def start():
    global _thread
    if _thread and _thread.is_alive():
        return
    _stop_event.clear()
    _thread = threading.Thread(target=_loop, daemon=True, name="rtqc-folder-watcher")
    _thread.start()


def stop():
    _stop_event.set()
