"""
watcher.py — Observa pastas locais/de rede em busca de novos arquivos DICOM
e analisa automaticamente com o pylinac, gravando o resultado direto no
banco (funciona mesmo sem nenhum navegador aberto).

Usa varredura por polling (em vez de eventos de sistema de arquivos) porque
pastas de rede mapeadas (ex.: um drive Z:\\ do Windows/SMB) frequentemente
não disparam notificações de mudança de forma confiável.
"""

import logging
import shutil
import tempfile
import threading
import time
from pathlib import Path

import db
from analysis import AnalysisError, run_analysis
from modules_config import MODULES

logger = logging.getLogger("rtqc-backend")

POLL_INTERVAL_SECONDS = 10
STABLE_CHECKS = 2  # nº de varreduras seguidas com o mesmo tamanho de arquivo para considerá-lo "pronto"
PROCESSED_SUBDIR = "processado_cq"
FAILED_SUBDIR = "falha_cq"

# Testes cujo input_mode não é "single" (ex.: Winston-Lutz = "multiple",
# VMAT DRGS/DRMLC = "pair") precisam de VÁRIAS imagens analisadas JUNTAS
# como um único exame — não faz sentido (e o próprio pylinac rejeita)
# analisar uma de cada vez. Para esses, o mínimo de arquivos exigido antes
# de sequer tentar a análise:
MIN_FILES_BY_MODE = {"pair": 2, "multiple": 2, "series": 1}

_stop_event = threading.Event()
_thread = None
_file_sizes = {}  # caminho -> (tamanho, nº de checagens estáveis)


def _wait_stable(path: Path) -> bool:
    try:
        size = path.stat().st_size
    except OSError:
        return False
    prev = _file_sizes.get(str(path))
    count = prev[1] + 1 if prev and prev[0] == size else 1
    _file_sizes[str(path)] = (size, count)
    return count >= STABLE_CHECKS


def _process_file(routine: dict, file_paths: list):
    """Roda a análise pylinac sobre um ou mais arquivos que pertencem ao
    MESMO exame (para testes "single" é sempre 1 arquivo; para "pair"/
    "multiple"/"series" é o lote inteiro coletado por _handle_watch_folder)
    e grava um único resultado automático."""
    tmp_dir = tempfile.mkdtemp(prefix="rtqc_watch_")
    try:
        saved_paths = []
        for file_path in file_paths:
            dest = Path(tmp_dir) / file_path.name
            shutil.copy(str(file_path), str(dest))
            saved_paths.append(dest)

        result = run_analysis(routine["moduleId"], routine["params"], saved_paths, tmp_dir)

        values = {}
        for m in routine["metrics"]:
            v = result["metrics"].get(m["key"])
            if v is not None:
                values[m["key"]] = v

        date = result["metrics"].get("dicom_study_date") or time.strftime("%Y-%m-%d")
        names = [p.name for p in file_paths]
        source_note = names[0] if len(names) == 1 else f"{len(names)} arquivos: {', '.join(names[:5])}" + (
            "..." if len(names) > 5 else ""
        )

        db.create_result(
            {
                "routineId": routine["id"],
                "date": date,
                "performedByName": "Análise automática (pasta observada)",
                "values": values,
                "notes": f"Gerado automaticamente a partir de {source_note}.",
                "analyzedWithPylinac": True,
                "autoGenerated": True,
                "rawMetrics": result["metrics"],
                "sourceFiles": names,
            }
        )
        logger.info("Resultado automático criado (rotina %s, %d arquivo(s))", routine["id"], len(file_paths))
        return True
    except AnalysisError as e:
        logger.warning("Falha ao analisar automaticamente %s: %s", [str(p) for p in file_paths], e)
        return False
    except Exception:
        logger.exception("Erro inesperado ao processar %s", [str(p) for p in file_paths])
        return False
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def _move_entries(entries, target_dir):
    try:
        target_dir.mkdir(exist_ok=True)
        for entry in entries:
            shutil.move(str(entry), str(target_dir / entry.name))
    except OSError as move_err:
        logger.warning("Não foi possível mover %s após processar: %s", [str(e) for e in entries], move_err)


def _handle_watch_folder(wf: dict):
    folder = Path(wf["folderPath"])
    if not folder.is_dir():
        db.set_watch_folder_error(wf["id"], f"Pasta não encontrada ou inacessível: {wf['folderPath']}")
        return

    routine = db.get_routine(wf["routineId"])
    if not routine:
        db.set_watch_folder_error(wf["id"], "A rotina associada a esta pasta não existe mais.")
        return

    processed_dir = folder / PROCESSED_SUBDIR
    failed_dir = folder / FAILED_SUBDIR

    try:
        entries = sorted(p for p in folder.iterdir() if p.is_file())
    except OSError as e:
        db.set_watch_folder_error(wf["id"], f"Erro ao listar a pasta: {e}")
        return

    input_mode = MODULES.get(routine.get("moduleId") or "", {}).get("input_mode", "single")

    if input_mode == "single":
        # Cada arquivo é o exame inteiro (ex.: Picket Fence, Starshot) — 1
        # arquivo estável = 1 resultado, processado assim que chega.
        for entry in entries:
            if not _wait_stable(entry):
                continue  # arquivo ainda sendo escrito/copiado; tenta de novo na próxima varredura
            ok = _process_file(routine, [entry])
            _file_sizes.pop(str(entry), None)
            _move_entries([entry], processed_dir if ok else failed_dir)
    else:
        # "pair"/"multiple"/"series": as imagens pertencem a UM MESMO exame
        # (ex.: Winston-Lutz precisa de todas as imagens de gantry/
        # colimador/mesa juntas para analisar — o pylinac rejeita menos de
        # 2). Só processa quando TODOS os arquivos hoje na pasta já
        # estiverem estáveis: se a exportação ainda estiver trazendo mais
        # arquivos, isso simplesmente adia o processamento para a próxima
        # varredura em vez de analisar um lote incompleto.
        stability = [_wait_stable(entry) for entry in entries]
        min_files = MIN_FILES_BY_MODE.get(input_mode, 1)
        if entries and all(stability) and len(entries) >= min_files:
            ok = _process_file(routine, entries)
            for entry in entries:
                _file_sizes.pop(str(entry), None)
            _move_entries(entries, processed_dir if ok else failed_dir)

    db.set_watch_folder_error(wf["id"], None)


def _loop():
    logger.info("Observador de pastas ativo (verificação a cada %ss).", POLL_INTERVAL_SECONDS)
    while not _stop_event.is_set():
        try:
            for wf in db.list_watch_folders(active_only=True):
                _handle_watch_folder(wf)
        except Exception:
            logger.exception("Erro no laço do observador de pastas")
        _stop_event.wait(POLL_INTERVAL_SECONDS)


def start():
    global _thread
    if _thread and _thread.is_alive():
        return
    _stop_event.clear()
    _thread = threading.Thread(target=_loop, daemon=True, name="rtqc-folder-watcher")
    _thread.start()


def stop():
    _stop_event.set()
